//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("okulModel", "FK_ogrenciler_siniflar", "siniflar", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(okulModel.siniflar), "ogrenciler", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(okulModel.ogrenciler))]

// Original file name:
// Generation date: 11.04.2017 11:07:45
namespace okulModel
{
    
    /// <summary>
    /// There are no comments for okulEntities in the schema.
    /// </summary>
    public partial class okulEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new okulEntities object using the connection string found in the 'okulEntities' section of the application configuration file.
        /// </summary>
        public okulEntities() : 
                base("name=okulEntities", "okulEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new okulEntities object.
        /// </summary>
        public okulEntities(string connectionString) : 
                base(connectionString, "okulEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new okulEntities object.
        /// </summary>
        public okulEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "okulEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for mesajlar in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<mesajlar> mesajlar
        {
            get
            {
                if ((this._mesajlar == null))
                {
                    this._mesajlar = base.CreateQuery<mesajlar>("[mesajlar]");
                }
                return this._mesajlar;
            }
        }
        private global::System.Data.Objects.ObjectQuery<mesajlar> _mesajlar;
        /// <summary>
        /// There are no comments for ogrenciler in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ogrenciler> ogrenciler
        {
            get
            {
                if ((this._ogrenciler == null))
                {
                    this._ogrenciler = base.CreateQuery<ogrenciler>("[ogrenciler]");
                }
                return this._ogrenciler;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ogrenciler> _ogrenciler;
        /// <summary>
        /// There are no comments for siniflar in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<siniflar> siniflar
        {
            get
            {
                if ((this._siniflar == null))
                {
                    this._siniflar = base.CreateQuery<siniflar>("[siniflar]");
                }
                return this._siniflar;
            }
        }
        private global::System.Data.Objects.ObjectQuery<siniflar> _siniflar;
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("[sysdiagrams]");
                }
                return this._sysdiagrams;
            }
        }
        private global::System.Data.Objects.ObjectQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// There are no comments for uyeler in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<uyeler> uyeler
        {
            get
            {
                if ((this._uyeler == null))
                {
                    this._uyeler = base.CreateQuery<uyeler>("[uyeler]");
                }
                return this._uyeler;
            }
        }
        private global::System.Data.Objects.ObjectQuery<uyeler> _uyeler;
        /// <summary>
        /// There are no comments for mesajlar in the schema.
        /// </summary>
        public void AddTomesajlar(mesajlar mesajlar)
        {
            base.AddObject("mesajlar", mesajlar);
        }
        /// <summary>
        /// There are no comments for ogrenciler in the schema.
        /// </summary>
        public void AddToogrenciler(ogrenciler ogrenciler)
        {
            base.AddObject("ogrenciler", ogrenciler);
        }
        /// <summary>
        /// There are no comments for siniflar in the schema.
        /// </summary>
        public void AddTosiniflar(siniflar siniflar)
        {
            base.AddObject("siniflar", siniflar);
        }
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
        /// <summary>
        /// There are no comments for uyeler in the schema.
        /// </summary>
        public void AddTouyeler(uyeler uyeler)
        {
            base.AddObject("uyeler", uyeler);
        }
    }
    /// <summary>
    /// There are no comments for okulModel.mesajlar in the schema.
    /// </summary>
    /// <KeyProperties>
    /// mesajId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="okulModel", Name="mesajlar")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class mesajlar : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new mesajlar object.
        /// </summary>
        /// <param name="mesajId">Initial value of mesajId.</param>
        /// <param name="mesajAd">Initial value of mesajAd.</param>
        /// <param name="mesajSoyad">Initial value of mesajSoyad.</param>
        /// <param name="mesajMail">Initial value of mesajMail.</param>
        /// <param name="mesajIcerik">Initial value of mesajIcerik.</param>
        public static mesajlar Createmesajlar(int mesajId, string mesajAd, string mesajSoyad, string mesajMail, string mesajIcerik)
        {
            mesajlar mesajlar = new mesajlar();
            mesajlar.mesajId = mesajId;
            mesajlar.mesajAd = mesajAd;
            mesajlar.mesajSoyad = mesajSoyad;
            mesajlar.mesajMail = mesajMail;
            mesajlar.mesajIcerik = mesajIcerik;
            return mesajlar;
        }
        /// <summary>
        /// There are no comments for Property mesajId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int mesajId
        {
            get
            {
                return this._mesajId;
            }
            set
            {
                this.OnmesajIdChanging(value);
                this.ReportPropertyChanging("mesajId");
                this._mesajId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("mesajId");
                this.OnmesajIdChanged();
            }
        }
        private int _mesajId;
        partial void OnmesajIdChanging(int value);
        partial void OnmesajIdChanged();
        /// <summary>
        /// There are no comments for Property mesajAd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mesajAd
        {
            get
            {
                return this._mesajAd;
            }
            set
            {
                this.OnmesajAdChanging(value);
                this.ReportPropertyChanging("mesajAd");
                this._mesajAd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mesajAd");
                this.OnmesajAdChanged();
            }
        }
        private string _mesajAd;
        partial void OnmesajAdChanging(string value);
        partial void OnmesajAdChanged();
        /// <summary>
        /// There are no comments for Property mesajSoyad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mesajSoyad
        {
            get
            {
                return this._mesajSoyad;
            }
            set
            {
                this.OnmesajSoyadChanging(value);
                this.ReportPropertyChanging("mesajSoyad");
                this._mesajSoyad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mesajSoyad");
                this.OnmesajSoyadChanged();
            }
        }
        private string _mesajSoyad;
        partial void OnmesajSoyadChanging(string value);
        partial void OnmesajSoyadChanged();
        /// <summary>
        /// There are no comments for Property mesajMail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mesajMail
        {
            get
            {
                return this._mesajMail;
            }
            set
            {
                this.OnmesajMailChanging(value);
                this.ReportPropertyChanging("mesajMail");
                this._mesajMail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mesajMail");
                this.OnmesajMailChanged();
            }
        }
        private string _mesajMail;
        partial void OnmesajMailChanging(string value);
        partial void OnmesajMailChanged();
        /// <summary>
        /// There are no comments for Property mesajIcerik in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string mesajIcerik
        {
            get
            {
                return this._mesajIcerik;
            }
            set
            {
                this.OnmesajIcerikChanging(value);
                this.ReportPropertyChanging("mesajIcerik");
                this._mesajIcerik = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("mesajIcerik");
                this.OnmesajIcerikChanged();
            }
        }
        private string _mesajIcerik;
        partial void OnmesajIcerikChanging(string value);
        partial void OnmesajIcerikChanged();
    }
    /// <summary>
    /// There are no comments for okulModel.ogrenciler in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ogrenciId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="okulModel", Name="ogrenciler")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ogrenciler : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ogrenciler object.
        /// </summary>
        /// <param name="ogrenciId">Initial value of ogrenciId.</param>
        /// <param name="ogrenciAdi">Initial value of ogrenciAdi.</param>
        /// <param name="ogrenciSoyadi">Initial value of ogrenciSoyadi.</param>
        /// <param name="ogrenciNo">Initial value of ogrenciNo.</param>
        public static ogrenciler Createogrenciler(int ogrenciId, string ogrenciAdi, string ogrenciSoyadi, int ogrenciNo)
        {
            ogrenciler ogrenciler = new ogrenciler();
            ogrenciler.ogrenciId = ogrenciId;
            ogrenciler.ogrenciAdi = ogrenciAdi;
            ogrenciler.ogrenciSoyadi = ogrenciSoyadi;
            ogrenciler.ogrenciNo = ogrenciNo;
            return ogrenciler;
        }
        /// <summary>
        /// There are no comments for Property ogrenciId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ogrenciId
        {
            get
            {
                return this._ogrenciId;
            }
            set
            {
                this.OnogrenciIdChanging(value);
                this.ReportPropertyChanging("ogrenciId");
                this._ogrenciId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ogrenciId");
                this.OnogrenciIdChanged();
            }
        }
        private int _ogrenciId;
        partial void OnogrenciIdChanging(int value);
        partial void OnogrenciIdChanged();
        /// <summary>
        /// There are no comments for Property ogrenciAdi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ogrenciAdi
        {
            get
            {
                return this._ogrenciAdi;
            }
            set
            {
                this.OnogrenciAdiChanging(value);
                this.ReportPropertyChanging("ogrenciAdi");
                this._ogrenciAdi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ogrenciAdi");
                this.OnogrenciAdiChanged();
            }
        }
        private string _ogrenciAdi;
        partial void OnogrenciAdiChanging(string value);
        partial void OnogrenciAdiChanged();
        /// <summary>
        /// There are no comments for Property ogrenciSoyadi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ogrenciSoyadi
        {
            get
            {
                return this._ogrenciSoyadi;
            }
            set
            {
                this.OnogrenciSoyadiChanging(value);
                this.ReportPropertyChanging("ogrenciSoyadi");
                this._ogrenciSoyadi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ogrenciSoyadi");
                this.OnogrenciSoyadiChanged();
            }
        }
        private string _ogrenciSoyadi;
        partial void OnogrenciSoyadiChanging(string value);
        partial void OnogrenciSoyadiChanged();
        /// <summary>
        /// There are no comments for Property ogrenciNo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ogrenciNo
        {
            get
            {
                return this._ogrenciNo;
            }
            set
            {
                this.OnogrenciNoChanging(value);
                this.ReportPropertyChanging("ogrenciNo");
                this._ogrenciNo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ogrenciNo");
                this.OnogrenciNoChanged();
            }
        }
        private int _ogrenciNo;
        partial void OnogrenciNoChanging(int value);
        partial void OnogrenciNoChanged();
        /// <summary>
        /// There are no comments for Property ogrenciSemt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ogrenciSemt
        {
            get
            {
                return this._ogrenciSemt;
            }
            set
            {
                this.OnogrenciSemtChanging(value);
                this.ReportPropertyChanging("ogrenciSemt");
                this._ogrenciSemt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ogrenciSemt");
                this.OnogrenciSemtChanged();
            }
        }
        private string _ogrenciSemt;
        partial void OnogrenciSemtChanging(string value);
        partial void OnogrenciSemtChanged();
        /// <summary>
        /// There are no comments for Property ogrenciFoto in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ogrenciFoto
        {
            get
            {
                return this._ogrenciFoto;
            }
            set
            {
                this.OnogrenciFotoChanging(value);
                this.ReportPropertyChanging("ogrenciFoto");
                this._ogrenciFoto = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ogrenciFoto");
                this.OnogrenciFotoChanged();
            }
        }
        private string _ogrenciFoto;
        partial void OnogrenciFotoChanging(string value);
        partial void OnogrenciFotoChanged();
        /// <summary>
        /// There are no comments for siniflar in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("okulModel", "FK_ogrenciler_siniflar", "siniflar")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public siniflar siniflar
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<siniflar>("okulModel.FK_ogrenciler_siniflar", "siniflar").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<siniflar>("okulModel.FK_ogrenciler_siniflar", "siniflar").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for siniflar in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<siniflar> siniflarReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<siniflar>("okulModel.FK_ogrenciler_siniflar", "siniflar");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<siniflar>("okulModel.FK_ogrenciler_siniflar", "siniflar", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for okulModel.siniflar in the schema.
    /// </summary>
    /// <KeyProperties>
    /// sinifId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="okulModel", Name="siniflar")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class siniflar : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new siniflar object.
        /// </summary>
        /// <param name="sinifId">Initial value of sinifId.</param>
        /// <param name="sinifAdi">Initial value of sinifAdi.</param>
        public static siniflar Createsiniflar(int sinifId, string sinifAdi)
        {
            siniflar siniflar = new siniflar();
            siniflar.sinifId = sinifId;
            siniflar.sinifAdi = sinifAdi;
            return siniflar;
        }
        /// <summary>
        /// There are no comments for Property sinifId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int sinifId
        {
            get
            {
                return this._sinifId;
            }
            set
            {
                this.OnsinifIdChanging(value);
                this.ReportPropertyChanging("sinifId");
                this._sinifId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("sinifId");
                this.OnsinifIdChanged();
            }
        }
        private int _sinifId;
        partial void OnsinifIdChanging(int value);
        partial void OnsinifIdChanged();
        /// <summary>
        /// There are no comments for Property sinifAdi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string sinifAdi
        {
            get
            {
                return this._sinifAdi;
            }
            set
            {
                this.OnsinifAdiChanging(value);
                this.ReportPropertyChanging("sinifAdi");
                this._sinifAdi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("sinifAdi");
                this.OnsinifAdiChanged();
            }
        }
        private string _sinifAdi;
        partial void OnsinifAdiChanging(string value);
        partial void OnsinifAdiChanged();
        /// <summary>
        /// There are no comments for ogrenciler in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("okulModel", "FK_ogrenciler_siniflar", "ogrenciler")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ogrenciler> ogrenciler
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ogrenciler>("okulModel.FK_ogrenciler_siniflar", "ogrenciler");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ogrenciler>("okulModel.FK_ogrenciler_siniflar", "ogrenciler", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for okulModel.sysdiagrams in the schema.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="okulModel", Name="sysdiagrams")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class sysdiagrams : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of name.</param>
        /// <param name="principal_id">Initial value of principal_id.</param>
        /// <param name="diagram_id">Initial value of diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property principal_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this.ReportPropertyChanging("principal_id");
                this._principal_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("principal_id");
                this.Onprincipal_idChanged();
            }
        }
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// There are no comments for Property diagram_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this.ReportPropertyChanging("diagram_id");
                this._diagram_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("diagram_id");
                this.Ondiagram_idChanged();
            }
        }
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// There are no comments for Property version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this.ReportPropertyChanging("version");
                this._version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("version");
                this.OnversionChanged();
            }
        }
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// There are no comments for Property definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] definition
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._definition);
            }
            set
            {
                this.OndefinitionChanging(value);
                this.ReportPropertyChanging("definition");
                this._definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("definition");
                this.OndefinitionChanged();
            }
        }
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
    }
    /// <summary>
    /// There are no comments for okulModel.uyeler in the schema.
    /// </summary>
    /// <KeyProperties>
    /// uyeId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="okulModel", Name="uyeler")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class uyeler : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new uyeler object.
        /// </summary>
        /// <param name="uyeId">Initial value of uyeId.</param>
        /// <param name="uyeAdi">Initial value of uyeAdi.</param>
        /// <param name="uyeSoyadi">Initial value of uyeSoyadi.</param>
        /// <param name="uyeKullaniciAdi">Initial value of uyeKullaniciAdi.</param>
        /// <param name="uyeSifre">Initial value of uyeSifre.</param>
        public static uyeler Createuyeler(int uyeId, string uyeAdi, string uyeSoyadi, string uyeKullaniciAdi, string uyeSifre)
        {
            uyeler uyeler = new uyeler();
            uyeler.uyeId = uyeId;
            uyeler.uyeAdi = uyeAdi;
            uyeler.uyeSoyadi = uyeSoyadi;
            uyeler.uyeKullaniciAdi = uyeKullaniciAdi;
            uyeler.uyeSifre = uyeSifre;
            return uyeler;
        }
        /// <summary>
        /// There are no comments for Property uyeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int uyeId
        {
            get
            {
                return this._uyeId;
            }
            set
            {
                this.OnuyeIdChanging(value);
                this.ReportPropertyChanging("uyeId");
                this._uyeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("uyeId");
                this.OnuyeIdChanged();
            }
        }
        private int _uyeId;
        partial void OnuyeIdChanging(int value);
        partial void OnuyeIdChanged();
        /// <summary>
        /// There are no comments for Property uyeAdi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uyeAdi
        {
            get
            {
                return this._uyeAdi;
            }
            set
            {
                this.OnuyeAdiChanging(value);
                this.ReportPropertyChanging("uyeAdi");
                this._uyeAdi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("uyeAdi");
                this.OnuyeAdiChanged();
            }
        }
        private string _uyeAdi;
        partial void OnuyeAdiChanging(string value);
        partial void OnuyeAdiChanged();
        /// <summary>
        /// There are no comments for Property uyeSoyadi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uyeSoyadi
        {
            get
            {
                return this._uyeSoyadi;
            }
            set
            {
                this.OnuyeSoyadiChanging(value);
                this.ReportPropertyChanging("uyeSoyadi");
                this._uyeSoyadi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("uyeSoyadi");
                this.OnuyeSoyadiChanged();
            }
        }
        private string _uyeSoyadi;
        partial void OnuyeSoyadiChanging(string value);
        partial void OnuyeSoyadiChanged();
        /// <summary>
        /// There are no comments for Property uyeKullaniciAdi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uyeKullaniciAdi
        {
            get
            {
                return this._uyeKullaniciAdi;
            }
            set
            {
                this.OnuyeKullaniciAdiChanging(value);
                this.ReportPropertyChanging("uyeKullaniciAdi");
                this._uyeKullaniciAdi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("uyeKullaniciAdi");
                this.OnuyeKullaniciAdiChanged();
            }
        }
        private string _uyeKullaniciAdi;
        partial void OnuyeKullaniciAdiChanging(string value);
        partial void OnuyeKullaniciAdiChanged();
        /// <summary>
        /// There are no comments for Property uyeSifre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uyeSifre
        {
            get
            {
                return this._uyeSifre;
            }
            set
            {
                this.OnuyeSifreChanging(value);
                this.ReportPropertyChanging("uyeSifre");
                this._uyeSifre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("uyeSifre");
                this.OnuyeSifreChanged();
            }
        }
        private string _uyeSifre;
        partial void OnuyeSifreChanging(string value);
        partial void OnuyeSifreChanged();
    }
}
